/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SuperWallet__factory } from "./SuperWallet__factory";
export { SuperWalletFactory__factory } from "./SuperWalletFactory__factory";
